id: I508C0048
legacy_id: P002957
ocr_import_info:
  bdrc_scan_id: W26569
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T03:33:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:47:02.035574+00:00'
last_modified: 2022-09-02 14:47:15.158561
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W26569
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW26569
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྡེ་དགེའི་ལོ་རྒྱུས།
  author: བློ་གྲོས་ཕུན་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.8801337263533565
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1GS52344:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS52344
      total_pages: 114
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS52344.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8801337263533565
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
