id: P002957
initial_creation_type: ocr
source_metadata:
  id: bdr:W26569
  title: སྡེ་དགེའི་ལོ་རྒྱུས
  author: ''
  volumes:
    4fbe592eedf64deeab8bcd876bcfadb7:
      image_group_id: I1GS52344
      title: ''
      volume_number: 1
      total_pages: 114
