id: P002957
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W26569
  title: སྡེ་དགེའི་ལོ་རྒྱུས
  author: ''
  volumes:
    4fbe592eedf64deeab8bcd876bcfadb7:
      image_group_id: I1GS52344
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
